name: MacOS make

on:
  push:
    branches: [ master, development, automation ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: brew install --HEAD https://gist.githubusercontent.com/Kronuz/96ac10fbd8472eb1e7566d740c4034f8/raw/gtest.rb
      run: tap ros/deps
      run: install gtest
      run: brew install pkgconfig libxml2 glibmm libxml++ jack liblo libsndfile
    - name: make
      run: cmake ./
