name: Windows make

on:
  push:
    branches: [ master, development, automation ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - name: dependencies
      shell: msys2 {0}
      run: PATH="$PATH;C:/msys64" pacman --noconfirm -Syu git make gcc pkg-config mingw-w64-x86_64-libxml++2.6 mingw-w64-x86_64-jack2 mingw-w64-x86_64-liblo mingw-w64-x86_64-libsndfile mingw-w64-x86_64-fftw mingw-w64-x86_64-gsl mingw-w64-x86_64-eigen mingw-w64-x86_64-gtkmm3 mingw-w64-x86_64-boost mingw-w64-x86_64-xxd mingw-w64-x86_64-gtksourceviewmm mingw-w64-x86_64-webkit2gtk mingw-w64-x86_64-libltc
    - name: make
      run: make
