name: Windows make

on:
  push:
    branches: [ master, development, automation ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - name: dependencies
      shell: msys2 {0}
      run: PATH="$PATH;C:/msys64" pacman --noconfirm -Syu git make gcc pkg-config libxml++2.6 jack2 liblo libsndfile fftw gsl eigen gtkmm3 boost libltc xxd gtksourceviewmm webkit2gtk
    - name: make
      run: make
