name: Windows make

on:
  push:
    branches: [ master, development, automation ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: mingw-get install msys
      	   pacman -S mingw-w64-i686-libxml++
    - name: make
      run: make
